M48
; DRILL file KiCad 10.0.4 date 2026-06-26T15:48:39
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-26T15:48:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X92.63Y-56.58
T2
X111.0Y-50.12
T1
X85.58Y-56.58G85X85.28Y-56.58
G05
M30
